version: '3.7'

services:


  ui:
    container_name: eventbrite-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true  #use polling to watch file changes